[package]
name = "hamilton"
version = "0.1.0"
authors = ["Andreas Longva <andreas.b.longva@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
serde = { version="1.0", features=["derive"] }
erased-serde = { version="0.3" }
once_cell = "1.2"

[dev-dependencies]
serde_json = "1.0"